/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import config.dbConnector;
import config.passwordHasher;
import config.session;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author sheila mae albarando
 */
public class adminChangePass extends javax.swing.JFrame {

    /**
     * Creates new form adminDash
     */
    public adminChangePass() {
        initComponents();
        dt();
        times();
    }
    
    public void dt(){
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("MMM/dd/yyyy");
        
        String dd = sdf.format(d);
        date.setText(dd);
    }
    
    Timer t;
    SimpleDateFormat st;
    public void times(){
        
        
        t = new Timer(0, new ActionListener(){
            public void actionPerformed(ActionEvent e){
                //thow new UnsupportedOperationException("Not supported yet");
            Date dt = new Date();
            st = new SimpleDateFormat("hh:mm:ss a");
            String tt =st.format(dt);
            time.setText(tt);
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        acc_user = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idDisplay = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SavePassword = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        curshow = new javax.swing.JLabel();
        curhide = new javax.swing.JLabel();
        currentPass = new javax.swing.JPasswordField();
        newshow = new javax.swing.JLabel();
        newhide = new javax.swing.JLabel();
        newPass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        conshow = new javax.swing.JLabel();
        conhide = new javax.swing.JLabel();
        confirmPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        acc_user.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        acc_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_user.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(acc_user);
        acc_user.setBounds(140, 90, 240, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user emote.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 20, 100, 110);

        idDisplay.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        idDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.add(idDisplay);
        idDisplay.setBounds(170, 50, 180, 30);

        date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(date);
        date.setBounds(150, 10, 110, 30);

        time.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(time);
        time.setBounds(260, 10, 110, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 390, 140);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Current Password");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(50, 120, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Enter New Password");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(50, 180, 130, 30);

        SavePassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SavePassword.setText("Save Password");
        SavePassword.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SavePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePasswordActionPerformed(evt);
            }
        });
        jPanel3.add(SavePassword);
        SavePassword.setBounds(220, 270, 120, 30);

        Back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel3.add(Back);
        Back.setBounds(50, 270, 120, 30);

        curshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-30.png"))); // NOI18N
        jPanel3.add(curshow);
        curshow.setBounds(310, 90, 30, 30);

        curhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide-Pass.png"))); // NOI18N
        curhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                curhideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                curhideMouseReleased(evt);
            }
        });
        jPanel3.add(curhide);
        curhide.setBounds(310, 90, 30, 30);

        currentPass.setForeground(new java.awt.Color(0, 0, 204));
        currentPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(currentPass);
        currentPass.setBounds(50, 90, 290, 30);

        newshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-30.png"))); // NOI18N
        jPanel3.add(newshow);
        newshow.setBounds(310, 150, 30, 30);

        newhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide-Pass.png"))); // NOI18N
        newhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                newhideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                newhideMouseReleased(evt);
            }
        });
        jPanel3.add(newhide);
        newhide.setBounds(310, 150, 30, 30);

        newPass.setForeground(new java.awt.Color(0, 0, 204));
        newPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(newPass);
        newPass.setBounds(50, 150, 290, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ADMIN CHANGE PASSWORD");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.add(jLabel8);
        jLabel8.setBounds(50, 20, 290, 40);

        conshow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-eye-30.png"))); // NOI18N
        jPanel3.add(conshow);
        conshow.setBounds(311, 210, 30, 30);

        conhide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hide-Pass.png"))); // NOI18N
        conhide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                conhideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                conhideMouseReleased(evt);
            }
        });
        jPanel3.add(conhide);
        conhide.setBounds(310, 210, 30, 30);

        confirmPass.setForeground(new java.awt.Color(0, 0, 204));
        confirmPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(confirmPass);
        confirmPass.setBounds(50, 210, 290, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Confirm Password");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(50, 240, 140, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 160, 390, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        session sess = session.getInstance();
        
        idDisplay.setText("USER ID:"+sess.getUid());
        
        acc_user.setText(""+sess.getFname()+" "+sess.getLname());
    }//GEN-LAST:event_formWindowActivated

    private void SavePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePasswordActionPerformed
        // TODO add your handling code here:
        try {
            dbConnector dbc = new dbConnector();
            session sess = session.getInstance();

            String sql = "SELECT * FROM tbl_user WHERE u_id = '" + sess.getUid() + "'";
            ResultSet rs = dbc.getData(sql);
            if (rs.next()) {
                String curPass = rs.getString("u_password");
                String curhash = passwordHasher.hashPassword(currentPass.getText());

                if (curPass.equals(curhash)) {
                    String newPassValue = newPass.getText();
                    String confirmPassValue = confirmPass.getText();

                    if (newPassValue.equals(confirmPassValue)) {
                        String npass = passwordHasher.hashPassword(newPassValue);
                        dbc.updateData("UPDATE tbl_user SET u_password = '" + npass + "'");
                        JOptionPane.showMessageDialog(null, "Password Successfully Updated!");
                        adminUsersForm uds = new adminUsersForm();
                        uds.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "New Password and Confirm Password do not match!");
                        newPass.setText("");
                        confirmPass.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Current Password is Incorrect!");
                }
            }

        } catch (SQLException | NoSuchAlgorithmException ex) {
            System.out.println("" + ex);
        }
    }//GEN-LAST:event_SavePasswordActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        adminUsersForm uds = new adminUsersForm();
        uds.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void curhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curhideMousePressed
        // TODO add your handling code here:
        curshow.setVisible(true);
        curhide.setVisible(false);
        currentPass.setEchoChar((char)0);
    }//GEN-LAST:event_curhideMousePressed

    private void curhideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_curhideMouseReleased
        // TODO add your handling code here:
        curshow.setVisible(false);
        curhide.setVisible(true);
        currentPass.setEchoChar('*');
    }//GEN-LAST:event_curhideMouseReleased

    private void newhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newhideMousePressed
        // TODO add your handling code here:
        newshow.setVisible(true);
        newhide.setVisible(false);
        newPass.setEchoChar((char)0);
    }//GEN-LAST:event_newhideMousePressed

    private void newhideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newhideMouseReleased
        // TODO add your handling code here:
        newshow.setVisible(false);
        newhide.setVisible(true);
        newPass.setEchoChar('*');
    }//GEN-LAST:event_newhideMouseReleased

    private void conhideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conhideMousePressed
        // TODO add your handling code here:
        conshow.setVisible(true);
        conhide.setVisible(false);
        confirmPass.setEchoChar((char)0);
    }//GEN-LAST:event_conhideMousePressed

    private void conhideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conhideMouseReleased
        // TODO add your handling code here:
        conshow.setVisible(false);
        conhide.setVisible(true);
        confirmPass.setEchoChar('*');
    }//GEN-LAST:event_conhideMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminChangePass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminChangePass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton SavePassword;
    public javax.swing.JLabel acc_user;
    private javax.swing.JPasswordField confirmPass;
    private javax.swing.JLabel conhide;
    private javax.swing.JLabel conshow;
    private javax.swing.JLabel curhide;
    private javax.swing.JPasswordField currentPass;
    private javax.swing.JLabel curshow;
    private javax.swing.JLabel date;
    private javax.swing.JLabel idDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JLabel newhide;
    private javax.swing.JLabel newshow;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
